#!/bin/sh
#
# Init script for the Billing componenct.
#
# chkconfig: 2345 99 05
# description: script for starting and stopping the Bulling component
#

# Source function library.
. /etc/init.d/functions

prog=/usr/bin/bc-data-server
name='data server'
lockfile=/var/lock/subsys/bc-data
pidfile=/var/run/bc/data.pid
user=_bc

RETVAL=0

start() {
	if [ ! -f "$lockfile" ]; then
		echo -n $"Starting $name: "
		daemon --user "$user" --pidfile "$pidfile" $prog &&
			success || failure
		RETVAL=$?
		echo
		[ $RETVAL = 0 ] && touch "$lockfile"
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping $name: "
	RETVAL=0
	killproc -p "$pidfile" $prog ||
		RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f "$lockfile"
	return $RETVAL
}

restart() {
	stop
	start
}

case $1 in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	condrestart|condreload)
		[ -f "$lockfile" ] && restart || :
		;;
	status)
		status -p "$pidfile" $prog
		RETVAL=$?
		;;
	*)

	echo $"Usage: $name {start|stop|restart|reload|condrestart|condreload|status}"
	exit 3
esac

exit $RETVAL
