#!/bin/sh
#
# Init script for the CROC Cloud componenct.
#
# chkconfig: 2345 99 05
# description: script for starting and stopping the CROC Cloud component
#

# Source function library.
. /etc/init.d/functions

prog=/usr/bin/c2-bc-server
name=c2-bc
lockfile=/var/lock/subsys/c2-bc
pidfile=/var/run/bc.pid
user=_c2

RETVAL=0

start() {
	if [ ! -f "$lockfile" ]; then
		echo -n $"Starting $name: "

		install -o "$user" -d "/var/run" &&
			daemon --user "$user" --pidfile "$pidfile" $prog &&
			success || failure
		RETVAL=$?
		echo
		[ $RETVAL = 0 ] && touch "$lockfile"
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping $name: "
	RETVAL=0
	for p in /var/run/bc-*.pid; do
		[ -f "$p" ] ||
			continue
		killproc -p "$p" $prog ||
			RETVAL=$?
	done
	killproc -p "$pidfile" $prog ||
		RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f "$lockfile"
	return $RETVAL
}

restart() {
	stop
	start
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	condrestart|condreload)
		[ -f "$lockfile" ] && restart || :
	;;
	status)
		status -p "$pidfile" $prog
		RETVAL=$?
	;;
	*)

	echo $"Usage: $name {start|stop|restart|reload|condrestart|condreload|status}"
	exit 3
esac

exit $RETVAL
